from __future__ import annotations

from typing import Dict


def vite_react_ts_tailwind_base_files(project_name: str) -> Dict[str, str]:
    return {
        'package.json': f"""{{\n  \"name\": \"{project_name}\",\n  \"private\": true,\n  \"version\": \"0.0.1\",\n  \"type\": \"module\",\n  \"scripts\": {{\n    \"dev\": \"vite\",\n    \"build\": \"tsc -b && vite build\",\n    \"preview\": \"vite preview\"\n  }},\n  \"dependencies\": {{\n    \"react\": \"^18.3.1\",\n    \"react-dom\": \"^18.3.1\",\n    \"react-router-dom\": \"^6.26.2\"\n  }},\n  \"devDependencies\": {{\n    \"@types/react\": \"^18.3.3\",\n    \"@types/react-dom\": \"^18.3.0\",\n    \"@vitejs/plugin-react\": \"^4.3.1\",\n    \"autoprefixer\": \"^10.4.20\",\n    \"postcss\": \"^8.4.41\",\n    \"tailwindcss\": \"^3.4.10\",\n    \"typescript\": \"^5.6.2\",\n    \"vite\": \"^5.4.2\"\n  }}\n}}\n""",
        'index.html': """<!doctype html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n    <title>Generated App</title>\n  </head>\n  <body>\n    <div id=\"root\"></div>\n    <script type=\"module\" src=\"/src/main.tsx\"></script>\n  </body>\n</html>\n""",
          'vite.config.ts': """import { defineConfig } from \"vite\";\nimport react from \"@vitejs/plugin-react\";\n\nexport default defineConfig({\n  // Important: preview is served from /preview/{projectId}/, not from domain root.\n  // Using a relative base ensures built asset URLs resolve correctly under that subpath.
      base: \"./\",\n  plugins: [react()],\n  server: { port: 5173 },\n});\n""",
        'tsconfig.json': """{\n  \"compilerOptions\": {\n    \"target\": \"ES2022\",\n    \"useDefineForClassFields\": true,\n    \"lib\": [\"ES2022\", \"DOM\", \"DOM.Iterable\"],\n    \"module\": \"ESNext\",\n    \"skipLibCheck\": true,\n    \"moduleResolution\": \"Bundler\",\n    \"resolveJsonModule\": true,\n    \"isolatedModules\": true,\n    \"noEmit\": true,\n    \"jsx\": \"react-jsx\",\n    \"strict\": true,\n    \"types\": [\"vite/client\"]\n  },\n  \"include\": [\"src\"]\n}\n""",
        'postcss.config.cjs': """module.exports = {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {},\n  },\n};\n""",
        'tailwind.config.cjs': """/** @type {import('tailwindcss').Config} */\nmodule.exports = {\n  content: [\"./index.html\", \"./src/**/*.{ts,tsx}\"],\n  theme: {\n    extend: {},\n  },\n  plugins: [],\n};\n""",
        'src/main.tsx': """import React from \"react\";\nimport ReactDOM from \"react-dom/client\";\nimport { BrowserRouter } from \"react-router-dom\";\nimport App from \"./App\";\nimport \"./styles.css\";\n\nfunction getRouterBasename(): string {\n  // Previews can be hosted under /preview/{projectId}/, /previews/{projectId}/, or /p/{projectId}/.\n  // BrowserRouter needs a basename so routes like /, /about, /contact resolve correctly under that prefix.\n  const path = window.location.pathname || \"/\";\n  const match = path.match(/^\\/(?:preview|previews|p)\\/[^/]+/);\n  return match ? match[0] : \"/\";\n}\n\nReactDOM.createRoot(document.getElementById(\"root\")!).render(\n  <React.StrictMode>\n    <BrowserRouter basename={getRouterBasename()}>\n      <App />\n    </BrowserRouter>\n  </React.StrictMode>\n);\n""",
        'src/styles.css': """@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n:root { color-scheme: light; }\n""",
        'src/App.tsx': """import { Routes, Route, Navigate } from \"react-router-dom\";\nimport Layout from \"./components/Layout\";\nimport NotFound from \"./pages/NotFound\";\n\n// Pages inserted by generator:\nimport Home from \"./pages/Home\";\n\nexport default function App() {\n  return (\n    <Routes>\n      <Route element={<Layout />}>\n        <Route path=\"/\" element={<Home />} />\n        {/* __ROUTES__ */}\n        <Route path=\"*\" element={<NotFound />} />\n      </Route>\n      <Route path=\"/404\" element={<NotFound />} />\n      <Route path=\"*\" element={<Navigate to=\"/404\" replace />} />\n    </Routes>\n  );\n}\n""",
        'src/components/Layout.tsx': """import { Outlet, NavLink } from \"react-router-dom\";\n\nconst linkBase =\n  \"px-3 py-2 rounded-lg text-sm font-medium hover:bg-gray-100 transition\";\nconst linkActive = \"bg-gray-100\";\n\nexport default function Layout() {\n  return (\n    <div className=\"min-h-screen bg-white text-gray-900\">\n      <header className=\"sticky top-0 z-10 border-b bg-white/80 backdrop-blur\">\n        <div className=\"mx-auto max-w-6xl px-4 py-3 flex items-center justify-between\">\n          <div className=\"font-semibold\">Generated App</div>\n          <nav className=\"flex items-center gap-1\">\n            <NavLink\n              to=\"/\"\n              className={({ isActive }) => `${linkBase} ${isActive ? linkActive : \"\"}`}\n              end\n            >\n              Home\n            </NavLink>\n            {/* __NAV__ */}\n          </nav>\n        </div>\n      </header>\n\n      <main className=\"mx-auto max-w-6xl px-4 py-10\">\n        <Outlet />\n      </main>\n\n      <footer className=\"border-t\">\n        <div className=\"mx-auto max-w-6xl px-4 py-6 text-sm text-gray-500\">\n          Built with CodeLaunchAI\n        </div>\n      </footer>\n    </div>\n  );\n}\n""",
        'src/pages/NotFound.tsx': """export default function NotFound() {\n  return (\n    <div className=\"space-y-3\">\n      <h1 className=\"text-2xl font-semibold\">Page not found</h1>\n      <p className=\"text-gray-600\">The page you are looking for doesn’t exist.</p>\n    </div>\n  );\n}\n""",
        'src/pages/Home.tsx': """export default function Home() {\n  return (\n    <div className=\"space-y-6\">\n      <h1 className=\"text-3xl font-semibold\">Welcome</h1>\n      <p className=\"text-gray-600\">\n        This is a generated React app. Ask the AI to add pages and features.\n      </p>\n    </div>\n  );\n}\n""",
        'README.md': f"""# {project_name}\n\nGenerated by CodeLaunchAI.\n\n## Run\n```bash\nnpm install\nnpm run dev\n```\n\n## Build\n\n```bash\nnpm run build\nnpm run preview\n```\n""",
    }